return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "shellcheck",
        "dockerfile-language-server",
        "docker-compose-language-service",
        "ansible-lint",
        "delve",
        "gofumpt",
        "goimports",
        "gomodifytags",
        "gopls",
        "helm-ls",
        "impl",
        "json-lsp",
        "lua-language-server",
        "markdownlint",
        "marksman",
        "shfmt",
        "stylua",
        "terraform-ls",
        "yaml-language-server",
        "hclfmt",
      },
    },
  },
}
